# Generated by Django 4.2.2 on 2023-06-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registration_timestamp',
            new_name='registration_date',
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
