# Generated by Django 4.2.2 on 2023-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_registration_timestamp_student_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(null=True),
        ),
    ]
