# Generated by Django 4.2.2 on 2023-06-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user_name_alter_student_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Femail'), ('U', 'Unknown')], default='F', max_length=1),
            preserve_default=False,
        ),
    ]
