# Generated by Django 4.2.2 on 2023-06-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chinses_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
