# Generated by Django 4.2.2 on 2023-06-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_chinses_name_student_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='chinses_name',
            new_name='chinese_name',
        ),
    ]
