# Generated by Django 4.2.2 on 2023-11-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('school_year', models.DateField()),
                ('course_description', models.CharField(max_length=255)),
                ('course_type', models.CharField(choices=[('L', 'Language'), ('E', 'Enrichment')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('recovery_email', models.CharField(max_length=255)),
                ('joined_date', models.DateField(null=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Femail'), ('U', 'Unknown')], max_length=1)),
                ('date_of_birth', models.DateField(null=True)),
                ('chinese_name', models.CharField(max_length=255, null=True)),
                ('joined_date', models.DateField(null=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('confirmation_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('school_year', models.DateField()),
                ('registration_date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField()),
                ('original_amount', models.FloatField()),
                ('amount_in_dollar', models.FloatField()),
                ('payment_method', models.CharField(choices=[('CA', 'CASH'), ('CH', 'Check'), ('EL', 'Electronic')], max_length=2)),
                ('payment_status', models.CharField(choices=[('FP', 'FullPayment'), ('PP', 'PartialPayment'), ('FR', 'FullRefund'), ('PR', 'PartialRefund')], max_length=2)),
                ('registration_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.registration', verbose_name='Related registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Payment sender')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='user.Registration', to='user.student'),
        ),
    ]
