# Generated by Django 4.2.2 on 2023-11-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recovery_email',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_sign_up_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sign_up_status',
            field=models.CharField(choices=[('S', 'SignedUp'), ('V', 'Verified')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
