# Generated by Django 4.2.7 on 2023-12-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_recovery_email_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
