# Generated by Django 4.2.7 on 2023-12-08 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_remove_payment_user_remove_registration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(default='luzhao', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Payment sender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(default='luzhao', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_id',
            field=models.ForeignKey(default='luzhao', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
