# Generated by Django 4.2.7 on 2024-01-31 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_description', models.CharField(max_length=255)),
                ('course_type', models.CharField(choices=[('L', 'Language'), ('E', 'Enrichment')], max_length=1)),
                ('course_status', models.CharField(choices=[('A', 'Active'), ('U', 'Unavailable')], max_length=1)),
                ('size_limit', models.IntegerField()),
                ('creation_date', models.DateField(null=True)),
                ('last_update_time', models.DateField(null=True)),
                ('creater_name', models.CharField(max_length=255)),
                ('cost', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(null=True)),
                ('sign_up_status', models.CharField(choices=[('S', 'SignedUp'), ('V', 'Verified')], max_length=1, null=True)),
                ('verification_code', models.CharField(max_length=255, null=True)),
                ('member_type', models.CharField(choices=[('P', 'Parent'), ('B', 'BoardMember'), ('V', 'Volunteer')], max_length=1, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Femail'), ('U', 'Unknown')], max_length=1)),
                ('date_of_birth', models.DateField(null=True)),
                ('chinese_name', models.CharField(max_length=255, null=True)),
                ('joined_date', models.DateField(null=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(max_length=255)),
                ('school_year', models.DateField()),
                ('registration_date', models.DateField()),
                ('expiration_date', models.DateField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField()),
                ('original_amount', models.FloatField()),
                ('amount_in_dollar', models.FloatField()),
                ('payment_method', models.CharField(choices=[('CA', 'CASH'), ('CH', 'Check'), ('EL', 'Electronic')], max_length=2)),
                ('payment_status', models.CharField(choices=[('FP', 'FullPayment'), ('PP', 'PartialPayment'), ('FR', 'FullRefund'), ('PR', 'PartialRefund')], max_length=2)),
                ('registration_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.registration', verbose_name='Related registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Payment sender')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='members.Registration', to='members.student'),
        ),
    ]
