# Generated by Django 4.2.7 on 2024-02-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update_person',
            field=models.CharField(default='luzhao', max_length=255),
            preserve_default=False,
        ),
    ]
