# Generated by Django 4.2.7 on 2023-12-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user_type',
            new_name='member_type',
        ),
    ]
