# Generated by Django 4.2.7 on 2023-12-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_user_type_member_member_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='course_id',
            new_name='course',
        ),
    ]
