# Generated by Django 4.2.7 on 2024-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_course_last_update_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='school_year',
            new_name='school_year_end',
        ),
        migrations.AddField(
            model_name='registration',
            name='school_year_start',
            field=models.DateField(default='2024-09-01'),
            preserve_default=False,
        ),
    ]
