# Generated by Django 4.2.7 on 2024-02-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_school_year_registration_school_year_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('D', 'DEACTIVATED')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
