# Generated by Django 4.2.7 on 2024-01-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_course_id_registration_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(null=True),
        ),
    ]
