# Generated by Django 4.2.7 on 2024-02-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_registration_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_update_date',
            field=models.DateField(null=True),
        ),
    ]
