# Generated by Django 4.2.7 on 2024-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='class_name',
            new_name='creater_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='school_year',
        ),
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('A', 'Active'), ('U', 'Unavailable')], default='U', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='creation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_update_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='U', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='size_limit',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='expiration_date',
            field=models.DateField(default='2024-07-01'),
            preserve_default=False,
        ),
    ]
