# Generated by Django 4.2.7 on 2024-02-04 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_registration_last_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registration_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.registration', verbose_name='Related registration'),
        ),
        migrations.CreateModel(
            name='Dropout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year_start', models.DateField()),
                ('school_year_end', models.DateField()),
                ('course_name', models.CharField(max_length=255)),
                ('original_registration_code', models.CharField(max_length=25)),
                ('dropout_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Dropout requester')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='dropout_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.dropout', verbose_name='Related dropout'),
        ),
    ]
