# Generated by Django 4.2.7 on 2024-02-04 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_payment_registration_code_dropout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration_status',
        ),
    ]
