# Generated by Django 4.2.7 on 2024-02-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_registration_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_udpate_date',
            field=models.DateField(default='2024-02-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='last_update_person',
            field=models.CharField(default='luzhao', max_length=255),
            preserve_default=False,
        ),
    ]
