# Generated by Django 4.2.7 on 2024-02-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_payment_last_udpate_date_payment_last_update_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropout',
            name='original_registration_code',
            field=models.CharField(max_length=225),
        ),
    ]
