# Generated by Django 4.2.7 on 2024-02-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_dropout_original_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.course'),
        ),
    ]
