# Generated by Django 4.2.7 on 2024-04-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_registration_on_waiting_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
