# Generated by Django 4.2.7 on 2024-04-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_course_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(max_length=1024),
        ),
    ]
