# Generated by Django 4.2.7 on 2024-04-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_course_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.CharField(default='Unassigned', max_length=255, null=True),
        ),
    ]
