# Generated by Django 4.2.7 on 2024-04-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_course_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='on_waiting_list',
            field=models.BooleanField(default=False),
        ),
    ]
