# Generated by Django 4.2.7 on 2024-04-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_registration_on_waiting_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year_start', models.DateField()),
                ('school_year_end', models.DateField()),
                ('assigned_date', models.DateField()),
                ('expiration_date', models.DateField(null=True)),
                ('last_update_date', models.DateField(null=True)),
                ('last_update_person', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.member')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(null=True, through='members.InstructorAssignment', to='members.member'),
        ),
    ]
