# Generated by Django 4.2.7 on 2024-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_instructorassignment_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(through='members.InstructorAssignment', to='members.member'),
        ),
    ]
