# Generated by Django 4.2.7 on 2024-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_start_time',
            field=models.TimeField(null=True),
        ),
    ]
