# Generated by Django 4.2.7 on 2024-04-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_course_course_end_time_course_course_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('EB', 'EARLY_BIRD'), ('BM', 'BOARD_MEMBER')], max_length=2)),
                ('type', models.CharField(choices=[('P', 'PERCENTAGE'), ('A', 'AMOUNT')], max_length=1)),
                ('dolloar_amount', models.FloatField(null=True)),
                ('percentage', models.FloatField(null=True)),
                ('expiration_date', models.DateField()),
                ('creation_date', models.DateField()),
                ('creator', models.CharField()),
            ],
        ),
    ]
