# Generated by Django 4.2.7 on 2024-04-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='EARLY_BIRD_CCL', max_length=255),
            preserve_default=False,
        ),
    ]
