# Generated by Django 4.2.7 on 2024-04-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='CCL_EARLY_BIRD', max_length=255),
        ),
    ]
