# Generated by Django 4.2.7 on 2024-05-01 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_alter_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.coupon')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='coupons',
            field=models.ManyToManyField(through='members.CouponUsageRecord', to='members.coupon'),
        ),
    ]
