# Generated by Django 4.2.7 on 2024-05-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_couponusagerecord_registration_coupons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='dolloar_amount',
            new_name='dollar_amount',
        ),
    ]
