# Generated by Django 4.2.7 on 2024-05-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_registration_textbook_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('last_update_date', models.DateField()),
                ('last_update_person', models.CharField(max_length=255)),
                ('last_udpate_person', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.course')),
            ],
        ),
    ]
