# Generated by Django 4.2.7 on 2024-05-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_classgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='book_cost',
            field=models.FloatField(null=True),
        ),
    ]
