# Generated by Django 4.2.7 on 2024-05-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_course_book_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_comment='Event name', max_length=255, null=True)),
                ('date', models.DateField()),
                ('school_year_start', models.DateField()),
                ('school_year_end', models.DateField()),
                ('creation_date', models.DateField()),
                ('last_update_date', models.DateField()),
                ('last_update_person', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='last_udpate_person',
        ),
    ]
