# Generated by Django 4.2.7 on 2024-06-18 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_alter_payment_dropout_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registration_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.registration', verbose_name='Related registration'),
        ),
    ]
