# Generated by Django 4.2.7 on 2024-08-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_alter_payment_registration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='term_signed_date',
            field=models.DateField(null=True),
        ),
    ]
