# Generated by Django 4.2.7 on 2024-09-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_member_term_signed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percentage',
            field=models.FloatField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='book_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(default=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='student',
            name='chinese_name',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_date',
            field=models.DateField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
    ]
